// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'document_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<DocumentService>>
abstract class DocumentService implements RustOpaqueInterface {
  Future<Uint8List> applyAction({
    required List<BlockActionDoc> actions,
    required FutureOr<String> Function(String, String) diffDeltas,
  });

  Future<void> applyUpdates({required List<Uint8List> updates});

  Future<DocumentState> getDocumentState();

  Future<Uint8List> initEmptyDoc();

  Future<Uint8List> mergeUpdates({required List<Uint8List> updates});

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<DocumentService> newInstance() =>
      RustLib.instance.api.crateDocDocumentServiceDocumentServiceNew();

  /// Setting a root node id in the root map
  Future<Uint8List> setRootNodeId({required String id});
}
